import { ArrowDownUp, ChevronRight, MapPin } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import type { Complaint } from '../types'
import { EmptyState, PriorityBadge, StatusBadge } from './UI'

type SortKey = 'priority' | 'updated' | 'due'
const priorityRank = { critical: 0, high: 1, medium: 2, low: 3 }

export function ComplaintTable({ complaints, routePrefix, selectedId, onSelect, defaultSort = 'priority' }: { complaints: Complaint[]; routePrefix: string; selectedId?: string; onSelect?: (id: string) => void; defaultSort?: SortKey }) {
  const [sort, setSort] = useState<SortKey>(defaultSort)
  const navigate = useNavigate()
  const sorted = useMemo(() => [...complaints].sort((a, b) => sort === 'priority' ? priorityRank[a.priority] - priorityRank[b.priority] || new Date(a.dueAt).getTime() - new Date(b.dueAt).getTime() : sort === 'updated' ? new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime() : new Date(a.dueAt).getTime() - new Date(b.dueAt).getTime()), [complaints, sort])
  if (!complaints.length) return <EmptyState title="No reports match" description="Adjust the filters to bring active infrastructure reports back into view." />
  const activate = (id: string) => onSelect ? onSelect(id) : navigate(`${routePrefix}/${id}`)
  return <div className="min-w-0 overflow-hidden border border-civic-border">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-civic-border bg-civic-surface px-4 py-3"><p className="eyebrow"><span className="data text-civic-text">{complaints.length}</span> work items</p><label className="flex items-center gap-2 text-xs text-civic-muted"><ArrowDownUp size={14} strokeWidth={1.6} />Sort<span className="sr-only">complaints by</span><select value={sort} onChange={event => setSort(event.target.value as SortKey)} className="rounded-sm border border-civic-border bg-civic-bg px-2 py-1.5 text-xs text-civic-text"><option value="priority">Priority first</option><option value="due">Due soonest</option><option value="updated">Recently updated</option></select></label></div>
    <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[780px] border-collapse text-left"><thead className="bg-civic-secondary"><tr>{['Priority', 'Report', 'Location', 'Status', 'Due', ''].map(label => <th key={label} scope="col" className="border-b border-civic-border px-4 py-3 font-mono text-[10px] font-medium uppercase tracking-[.14em] text-civic-muted">{label}</th>)}</tr></thead><tbody className="divide-y divide-civic-border">{sorted.map(item => <tr key={item.id} tabIndex={0} onClick={() => activate(item.id)} onKeyDown={event => { if (event.key === 'Enter') activate(item.id) }} className={`cursor-pointer bg-civic-surface transition-colors hover:bg-civic-secondary/75 ${selectedId === item.id ? 'border-l-2 border-l-civic-accent bg-civic-secondary' : ''}`}><td className="px-4 py-3"><PriorityBadge priority={item.priority} /></td><td className="max-w-[300px] px-4 py-3"><p className="data text-[10px] text-civic-muted">{item.id}</p><p className="mt-1 truncate text-sm font-medium text-civic-text">{item.title}</p></td><td className="max-w-[250px] px-4 py-3"><span className="flex items-center gap-2 truncate text-xs text-civic-muted"><MapPin className="shrink-0" size={14} strokeWidth={1.6} />{item.location.address}</span></td><td className="px-4 py-3"><StatusBadge status={item.status} /></td><td className="data whitespace-nowrap px-4 py-3 text-xs text-civic-muted">{new Date(item.dueAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</td><td className="px-4 py-3 text-right"><ChevronRight className="inline text-civic-muted" size={16} strokeWidth={1.6} /></td></tr>)}</tbody></table></div>
    <div className="divide-y divide-civic-border md:hidden">{sorted.map(item => <button key={item.id} onClick={() => activate(item.id)} className={`block w-full px-4 py-4 text-left ${selectedId === item.id ? 'bg-civic-secondary' : 'bg-civic-surface'}`}><div className="flex items-center justify-between gap-3"><PriorityBadge priority={item.priority} /><span className="data text-[10px] text-civic-muted">{item.id}</span></div><p className="mt-2 text-sm font-medium text-civic-text">{item.title}</p><p className="mt-2 truncate text-xs text-civic-muted">{item.location.address}</p><div className="mt-3 flex items-center justify-between"><StatusBadge status={item.status} /><ChevronRight className="text-civic-muted" size={16} strokeWidth={1.6} /></div></button>)}</div>
  </div>
}
