import { AnimatePresence, motion } from 'framer-motion'
import { Activity, AlertTriangle, BarChart3, CheckCircle2, Download, Filter, MapPin, RefreshCw, Search, Settings2, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { CivicMap } from '../components/CivicMap'
import { ComplaintTable } from '../components/ComplaintTable'
import { AsyncBanner, Button, IconButton, Metric, PriorityBadge, SectionHeading, StatusBadge } from '../components/UI'
import { useApp } from '../context/AppContext'
import type { ComplaintStatus, Priority } from '../types'

const priorityColor: Record<Priority, string> = { critical: '#DC2626', high: '#D97706', medium: '#2563EB', low: '#16A34A' }
const tooltipStyle = { background: '#111827', border: '1px solid #263244', borderRadius: 2, color: '#F8FAFC', fontSize: 12 }

export default function AdminDashboard() {
  const { complaints, demoMode, setDemoMode, resetDemo, refreshComplaints } = useApp()
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState<ComplaintStatus | 'all'>('all')
  const [priority, setPriority] = useState<Priority | 'all'>('all')
  const [selected, setSelected] = useState<string>()
  const [state, setState] = useState<'idle' | 'loading' | 'success' | 'error'>('idle')
  const filtered = useMemo(() => complaints.filter(item => status === 'all' || item.status === status).filter(item => priority === 'all' || item.priority === priority).filter(item => `${item.id} ${item.title} ${item.location.address} ${item.department}`.toLowerCase().includes(search.toLowerCase())), [complaints, search, status, priority])
  const selectedComplaint = complaints.find(item => item.id === selected)
  const categoryData = useMemo(() => Object.entries(complaints.reduce<Record<string, number>>((all, item) => ({ ...all, [item.category]: (all[item.category] || 0) + 1 }), {})).map(([name, reports]) => ({ name, reports })).sort((a, b) => b.reports - a.reports), [complaints])
  const trendData = [{ day: 'Aug 17', received: 7, resolved: 3 }, { day: 'Aug 18', received: 5, resolved: 4 }, { day: 'Aug 19', received: 9, resolved: 6 }, { day: 'Aug 20', received: 6, resolved: 8 }, { day: 'Aug 21', received: 11, resolved: 7 }, { day: 'Aug 22', received: 8, resolved: 9 }, { day: 'Aug 23', received: 12, resolved: 8 }]
  const priorityData = (['critical', 'high', 'medium', 'low'] as Priority[]).map(name => ({ name, value: complaints.filter(item => item.priority === name).length }))
  const refresh = async () => { setState('loading'); try { const source = await refreshComplaints(); setState('success'); window.setTimeout(() => setState('idle'), 1800); if (source === 'demo') setDemoMode(true) } catch { setState('error') } }
  const exportCsv = () => { const rows = [['ID','Title','Category','Priority','Status','Address','Department'], ...filtered.map(item => [item.id,item.title,item.category,item.priority,item.status,item.location.address,item.department])]; const csv = rows.map(row => row.map(cell => `"${cell.replace(/"/g,'""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = `civictrack-operations-${new Date().toISOString().slice(0,10)}.csv`; link.click(); URL.revokeObjectURL(url) }
  const clear = () => { setSearch(''); setStatus('all'); setPriority('all') }
  return <div className="space-y-7"><SectionHeading eyebrow="Municipal operations / citywide" title="Command center" description="Live infrastructure demand, field capacity, and public service performance." action={<div className="flex gap-2"><Button variant="secondary" icon={Download} onClick={exportCsv}>Export</Button><Button variant="secondary" icon={RefreshCw} loading={state === 'loading'} onClick={refresh}>Refresh</Button></div>}/>
    <AsyncBanner state={state} success="Operations data is current." error="Live API refresh failed. The saved operations snapshot remains active."/>
    <section className="grid grid-cols-2 gap-4 xl:grid-cols-5"><Metric label="Open reports" value={complaints.filter(item => !['resolved','rejected'].includes(item.status)).length} detail="Across all services"/><Metric label="Critical" value={complaints.filter(item => item.priority === 'critical' && item.status !== 'resolved').length} detail="Immediate intervention" tone="critical"/><Metric label="Resolved / 7d" value={complaints.filter(item => item.status === 'resolved').length} detail="With field evidence" tone="success"/><Metric label="Median response" value="4.2h" detail="Down 36 min this week"/><Metric label="SLA health" value="87.4%" detail="Within service target"/></section>
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(360px,.65fr)]"><div className="panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-civic-border px-4 py-3"><div className="flex items-center gap-2"><MapPin size={15} strokeWidth={1.6} className="text-civic-accent"/><p className="eyebrow">Operational map</p></div><div className="flex gap-4">{(['critical','high','medium','low'] as Priority[]).map(item => <span key={item} className="hidden items-center gap-1.5 font-mono text-[9px] uppercase text-civic-muted sm:flex"><span className="h-1.5 w-1.5 rounded-full" style={{ backgroundColor: priorityColor[item] }}/>{item}</span>)}</div></div><CivicMap complaints={filtered} selectedId={selected} onSelect={setSelected} routePrefix="/admin/complaints" className="h-[480px] border-0"/></div>
      <div className="panel"><div className="flex items-center justify-between border-b border-civic-border p-4"><div className="flex items-center gap-2"><BarChart3 size={15} strokeWidth={1.6} className="text-civic-accent"/><p className="eyebrow">Priority load</p></div><span className="data text-[10px] text-civic-muted">ACTIVE / {complaints.length}</span></div><div className="h-[270px] p-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={priorityData} margin={{ top: 10, right: 4, left: -25, bottom: 0 }}><CartesianGrid stroke="#263244" vertical={false}/><XAxis dataKey="name" stroke="#94A3B8" tick={{ fill: '#94A3B8', fontSize: 10 }} tickLine={false} axisLine={false}/><YAxis allowDecimals={false} stroke="#94A3B8" tick={{ fill: '#94A3B8', fontSize: 10 }} tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle}/><Bar dataKey="value" radius={0}>{priorityData.map(entry => <Cell key={entry.name} fill={priorityColor[entry.name]}/>)}</Bar></BarChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-px bg-civic-border border-t border-civic-border">{priorityData.map(item => <button key={item.name} onClick={() => setPriority(priority === item.name ? 'all' : item.name)} className={`bg-civic-surface p-3 text-left hover:bg-civic-secondary ${priority === item.name ? 'border-l-2 border-civic-accent' : ''}`}><p className="font-mono text-[9px] uppercase tracking-[.12em] text-civic-muted">{item.name}</p><p className="data mt-1 text-lg">{item.value}</p></button>)}</div></div>
    </section>
    <section className="panel"><div className="flex items-center justify-between border-b border-civic-border px-4 py-3"><div className="flex items-center gap-2"><Filter size={15} strokeWidth={1.6} className="text-civic-muted"/><p className="eyebrow">Case matrix</p></div><button onClick={clear} className="text-xs text-civic-muted hover:text-civic-text">Clear filters</button></div><div className="grid gap-3 p-4 md:grid-cols-[1fr_180px_180px]"><label className="relative"><span className="sr-only">Search cases</span><Search className="absolute left-3 top-3 text-civic-muted" size={16} strokeWidth={1.6}/><input className="field py-2.5 pl-9" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search ID, issue, address, or service"/></label><select aria-label="Filter by status" className="field py-2.5" value={status} onChange={event => setStatus(event.target.value as ComplaintStatus | 'all')}><option value="all">All statuses</option><option value="submitted">Submitted</option><option value="verified">Verified</option><option value="assigned">Assigned</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option></select><select aria-label="Filter by priority" className="field py-2.5" value={priority} onChange={event => setPriority(event.target.value as Priority | 'all')}><option value="all">All priorities</option><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></div></section>
    <ComplaintTable complaints={filtered} routePrefix="/admin/complaints" selectedId={selected} onSelect={setSelected}/>
    <section className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="panel"><div className="flex items-center gap-2 border-b border-civic-border p-4"><Activity size={15} strokeWidth={1.6} className="text-civic-accent"/><p className="eyebrow">Seven-day throughput</p></div><div className="h-[300px] p-4"><ResponsiveContainer width="100%" height="100%"><LineChart data={trendData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}><CartesianGrid stroke="#263244" vertical={false}/><XAxis dataKey="day" tick={{ fill: '#94A3B8', fontSize: 10 }} tickLine={false} axisLine={false}/><YAxis tick={{ fill: '#94A3B8', fontSize: 10 }} tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle}/><Line type="monotone" dataKey="received" stroke="#2563EB" strokeWidth={2} dot={{ fill: '#2563EB', r: 3 }} activeDot={{ r: 5 }}/><Line type="monotone" dataKey="resolved" stroke="#16A34A" strokeWidth={2} dot={{ fill: '#16A34A', r: 3 }}/></LineChart></ResponsiveContainer></div><div className="flex gap-5 border-t border-civic-border px-4 py-3 font-mono text-[9px] uppercase tracking-[.12em] text-civic-muted"><span className="flex items-center gap-2"><span className="h-0.5 w-5 bg-civic-accent"/>Received</span><span className="flex items-center gap-2"><span className="h-0.5 w-5 bg-civic-success"/>Resolved</span></div></div>
      <div className="panel"><div className="flex items-center justify-between border-b border-civic-border p-4"><p className="eyebrow">Demand by service</p><span className="data text-[10px] text-civic-muted">{categoryData.length} types</span></div><div className="divide-y divide-civic-border">{categoryData.map((item,index) => <div key={item.name} className="grid grid-cols-[1fr_80px_30px] items-center gap-3 px-4 py-3"><div><p className="text-xs text-civic-text">{item.name}</p><div className="mt-2 h-1 bg-civic-bg"><div className="h-full bg-civic-accent" style={{ width: `${item.reports / categoryData[0].reports * 100}%` }}/></div></div><span className="data text-right text-xs text-civic-muted">{Math.round(item.reports / complaints.length * 100)}%</span><span className="data text-right text-xs">{item.reports}</span></div>)}</div></div></section>
    <section className="flex flex-col gap-4 border-t border-civic-border pt-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><Settings2 size={16} strokeWidth={1.6} className="text-civic-muted"/><div><p className="text-xs font-medium">Developer data source</p><p className="mt-1 text-[10px] text-civic-muted">Small operational control; resident views do not expose this switch.</p></div></div><div className="flex flex-wrap items-center gap-2"><button role="switch" aria-checked={demoMode} onClick={() => setDemoMode(!demoMode)} className={`relative h-6 w-11 rounded-full border transition-colors ${demoMode ? 'border-civic-warning bg-civic-warning/25' : 'border-civic-success bg-civic-success/25'}`}><span className={`absolute top-1 h-3.5 w-3.5 rounded-full bg-civic-text transition-transform ${demoMode ? 'translate-x-1' : 'translate-x-6'}`}/><span className="sr-only">Toggle demo mode</span></button><span className="font-mono text-[9px] uppercase tracking-[.12em] text-civic-muted">{demoMode ? 'Demo AI' : 'Live AI'}</span><Button variant="ghost" onClick={resetDemo}>Reset demo</Button></div></section>
    <AnimatePresence>{selectedComplaint && <><motion.button aria-label="Close complaint drawer" className="fixed inset-0 z-[650] bg-civic-bg/70" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setSelected(undefined)}/><motion.aside role="dialog" aria-modal="true" aria-label={`Details for ${selectedComplaint.id}`} initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }} transition={{ type: 'spring', stiffness: 230, damping: 28 }} className="fixed inset-y-0 right-0 z-[700] w-full max-w-lg overflow-y-auto border-l border-civic-border bg-civic-surface shadow-panel"><div className="sticky top-0 flex items-center justify-between border-b border-civic-border bg-civic-surface px-5 py-4"><div><p className="eyebrow">Case inspection</p><p className="data mt-1 text-sm">{selectedComplaint.id}</p></div><IconButton icon={X} label="Close drawer" onClick={() => setSelected(undefined)}/></div><div className="p-5 sm:p-7"><img src={selectedComplaint.imageUrl} alt="Reported infrastructure condition" className="aspect-video w-full border border-civic-border object-cover"/><div className="mt-5 flex items-center justify-between gap-3"><PriorityBadge priority={selectedComplaint.priority}/><StatusBadge status={selectedComplaint.status}/></div><h2 className="mt-5 text-2xl font-semibold tracking-tight">{selectedComplaint.title}</h2><p className="mt-3 flex gap-2 text-sm text-civic-muted"><MapPin className="mt-0.5 shrink-0" size={16} strokeWidth={1.6}/>{selectedComplaint.location.address}</p><p className="mt-5 text-sm leading-6 text-civic-muted">{selectedComplaint.description}</p><div className="mt-7 grid grid-cols-2 gap-px border border-civic-border bg-civic-border">{[['AI confidence',`${selectedComplaint.confidence}%`],['Severity',`${selectedComplaint.severityScore.toFixed(1)}/10`],['Department',selectedComplaint.department],['Updated',new Date(selectedComplaint.updatedAt).toLocaleString()]].map(([label,value]) => <div key={label} className="bg-civic-bg p-4"><p className="eyebrow">{label}</p><p className="mt-2 text-sm">{value}</p></div>)}</div><div className="mt-7"><p className="eyebrow">Recent activity</p><div className="mt-3 divide-y divide-civic-border border-y border-civic-border">{selectedComplaint.timeline.slice(-3).reverse().map(item => <div key={item.id} className="py-3"><div className="flex justify-between gap-3"><p className="text-xs font-medium">{item.title}</p><time className="data text-[9px] text-civic-muted">{new Date(item.timestamp).toLocaleDateString()}</time></div><p className="mt-1 text-[11px] leading-5 text-civic-muted">{item.description}</p></div>)}</div></div>{selectedComplaint.status === 'resolved' && <Link to={`/verification/${selectedComplaint.id}`} className="mt-7 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-md bg-civic-success px-4 text-sm font-semibold text-white"><CheckCircle2 size={16} strokeWidth={1.6}/>Open verified result</Link>}</div></motion.aside></>}</AnimatePresence>
  </div>
}
