import { AnimatePresence, motion } from 'framer-motion'
import { ArrowLeft, CalendarClock, Check, CheckCircle2, Clipboard, Eye, GitBranch, MapPin, Navigation, ShieldCheck, Sparkles, UserRound } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { CivicMap } from '../components/CivicMap'
import { Button, PriorityBadge, StatusBadge } from '../components/UI'
import { useApp } from '../context/AppContext'

export default function CitizenDetail() {
  const { id = '' } = useParams()
  const { complaintById } = useApp()
  const complaint = complaintById(id)
  const navigate = useNavigate()
  const [copied, setCopied] = useState(false)
  if (!complaint) return <div className="panel p-8"><p className="eyebrow">Report unavailable</p><h1 className="mt-3 text-2xl font-semibold">We could not find {id}</h1><p className="mt-3 text-sm text-civic-muted">The report may have been removed or belongs to another resident.</p><Button className="mt-6" variant="secondary" icon={ArrowLeft} onClick={() => navigate('/citizen')}>Back to my reports</Button></div>
  const copy = async () => { try { await navigator.clipboard.writeText(window.location.href); setCopied(true); window.setTimeout(() => setCopied(false), 1800) } catch { setCopied(false) } }
  const latest = complaint.timeline[complaint.timeline.length - 1]
  return <div className="space-y-7">
    <div className="flex flex-wrap items-center justify-between gap-3"><button onClick={() => navigate('/citizen')} className="inline-flex items-center gap-2 text-sm text-civic-muted hover:text-civic-text"><ArrowLeft size={16} strokeWidth={1.6}/>My reports</button><Button variant="secondary" icon={copied ? Check : Clipboard} onClick={copy}>{copied ? 'Tracking link copied' : 'Copy tracking link'}</Button></div>
    <header className="grid gap-5 border-b border-civic-border pb-7 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="flex flex-wrap items-center gap-3"><span className="data text-xs text-civic-muted">{complaint.id}</span><PriorityBadge priority={complaint.priority}/><StatusBadge status={complaint.status}/></div><h1 className="mt-4 max-w-3xl text-3xl font-semibold tracking-tight sm:text-4xl">{complaint.title}</h1><p className="mt-4 flex items-start gap-2 text-sm text-civic-muted"><MapPin className="mt-0.5 shrink-0" size={16} strokeWidth={1.6}/>{complaint.location.address}</p></div><div className="border-l-2 border-civic-accent bg-civic-secondary px-4 py-3"><p className="eyebrow">Latest public update</p><p className="mt-2 text-sm font-medium">{latest.title}</p><p className="data mt-1 text-[10px] text-civic-muted">{new Date(latest.timestamp).toLocaleString()}</p></div></header>
    {complaint.status === 'resolved' && <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="flex flex-col justify-between gap-4 border border-civic-success/40 bg-civic-success/10 p-5 sm:flex-row sm:items-center"><div className="flex gap-3"><CheckCircle2 className="shrink-0 text-green-300" size={22} strokeWidth={1.6}/><div><p className="font-semibold text-green-200">Repair complete and field-verified</p><p className="mt-1 text-xs text-civic-muted">Before-and-after evidence is ready for public review.</p></div></div><Link to={`/verification/${complaint.id}`} className="inline-flex min-h-10 items-center justify-center rounded-md bg-civic-success px-4 text-sm font-semibold text-white">View verified result</Link></motion.div>}
    <div className="grid gap-7 xl:grid-cols-[minmax(0,1.25fr)_minmax(340px,.75fr)]">
      <div className="space-y-7"><section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-civic-border px-5 py-4"><div><p className="eyebrow">Location</p><p className="mt-1 text-sm text-civic-text">Field coordinates <span className="data ml-2 text-[10px] text-civic-muted">{complaint.location.lat.toFixed(4)}, {complaint.location.lng.toFixed(4)}</span></p></div><a href={`https://www.openstreetmap.org/?mlat=${complaint.location.lat}&mlon=${complaint.location.lng}#map=18/${complaint.location.lat}/${complaint.location.lng}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-xs font-semibold text-blue-300"><Navigation size={14} strokeWidth={1.6}/>Open map</a></div><CivicMap complaints={[complaint]} selectedId={complaint.id} className="h-[340px] border-0"/></section>
        <section><div className="mb-5"><p className="eyebrow">Evidence record</p><h2 className="mt-2 text-xl font-semibold">Field captures</h2></div><div className="grid gap-4 sm:grid-cols-2">{complaint.evidence.map(item => <figure key={item.id} className="overflow-hidden border border-civic-border bg-civic-surface"><img src={item.url} alt={`${item.type} evidence for ${complaint.id}`} className="aspect-[16/10] w-full object-cover"/><figcaption className="border-t border-civic-border p-4"><div className="flex justify-between gap-3"><span className="font-mono text-[10px] uppercase tracking-[.14em] text-civic-text">{item.type} evidence</span><span className="data text-[10px] text-civic-muted">{new Date(item.timestamp).toLocaleDateString()}</span></div><p className="mt-2 text-xs text-civic-muted">{item.note}</p></figcaption></figure>)}</div></section>
      </div>
      <aside className="space-y-7"><section className="panel p-5 sm:p-6"><div className="flex items-center gap-2"><CalendarClock size={17} strokeWidth={1.6} className="text-civic-accent"/><p className="eyebrow">Resolution timeline</p></div><div className="mt-6">{complaint.timeline.map((item, index) => <motion.div initial={{ opacity: 0, x: 8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .06 }} key={item.id} className="relative grid grid-cols-[28px_1fr] gap-3 pb-7 last:pb-0"><div className="relative"><span className={`relative z-[1] grid h-7 w-7 place-items-center rounded-full border ${index === complaint.timeline.length - 1 ? 'border-civic-accent bg-civic-accent text-white' : 'border-civic-success/50 bg-civic-success/10 text-green-300'}`}><Check size={13} strokeWidth={1.6}/></span>{index < complaint.timeline.length - 1 && <span className="absolute left-[13px] top-7 h-full w-px bg-civic-border"/>}</div><div><p className="text-sm font-semibold text-civic-text">{item.title}</p><p className="mt-1 text-xs leading-5 text-civic-muted">{item.description}</p><div className="mt-2 flex justify-between gap-3 font-mono text-[9px] uppercase tracking-[.1em] text-civic-muted"><span>{item.actor}</span><time>{new Date(item.timestamp).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}</time></div></div></motion.div>)}</div></section>
        <section className="border border-civic-border bg-civic-secondary"><div className="p-5 sm:p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Eye size={17} strokeWidth={1.6} className="text-blue-300"/><p className="eyebrow">Vision analysis</p></div><span className="data text-xs text-blue-300">{complaint.confidence}%</span></div><p className="mt-4 text-sm leading-6 text-civic-text">{complaint.aiSummary}</p><div className="mt-5 grid grid-cols-2 gap-4 border-t border-civic-border pt-4"><div><p className="eyebrow">Detected issue</p><p className="mt-1 text-sm">{complaint.category}</p></div><div><p className="eyebrow">Infrastructure</p><p className="mt-1 text-sm">{complaint.category === 'Pothole' ? 'Road' : complaint.category}</p></div><div><p className="eyebrow">Visual severity</p><p className="data mt-1 text-lg">{complaint.severityScore.toFixed(1)}/10</p></div><div><p className="eyebrow">Confidence</p><p className="data mt-1 text-lg">{complaint.confidence}%</p></div></div></div><div className="border-t border-civic-border p-5 sm:p-6"><div className="flex items-center gap-2"><GitBranch size={17} strokeWidth={1.6} className="text-civic-warning"/><p className="eyebrow">Decision engine</p></div><div className="mt-4 grid grid-cols-2 gap-4"><div><p className="eyebrow">Department</p><p className="mt-1 text-sm">{complaint.department}</p></div><div><p className="eyebrow">SLA target</p><p className="data mt-1 text-lg">{complaint.priority === 'critical' ? 6 : complaint.priority === 'high' ? 12 : complaint.priority === 'medium' ? 48 : 120}h</p></div><div><p className="eyebrow">Priority</p><p className="data mt-1 text-lg uppercase">{complaint.priority}</p></div><div><p className="eyebrow">Score</p><p className="data mt-1 text-lg">{complaint.priorityScore ?? Math.round(complaint.severityScore * 9)}/100</p></div></div><div className="mt-5 space-y-3 border-t border-civic-border pt-4"><p className="eyebrow">Why this decision</p>{complaint.aiReasoning.map(reason => <div key={reason} className="flex gap-2 text-xs leading-5 text-civic-muted"><Sparkles className="mt-0.5 shrink-0 text-civic-accent" size={14} strokeWidth={1.6}/>{reason}</div>)}</div><div className="mt-5"><p className="eyebrow">Duplicate confidence</p><p className="data mt-1 text-lg">{Math.round(complaint.duplicateRisk * 100)}%</p></div></div></section>
        <section className="border-l-2 border-civic-border pl-4"><div className="flex gap-3"><UserRound className="shrink-0 text-civic-muted" size={18} strokeWidth={1.6}/><div><p className="text-sm font-medium">Assigned service</p><p className="mt-1 text-xs text-civic-muted">{complaint.department}</p><p className="mt-1 text-xs text-civic-muted">{complaint.assignedOfficerName || 'Awaiting crew assignment'}</p></div></div></section>
      </aside>
    </div>
    <AnimatePresence>{copied && <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} role="status" className="fixed bottom-5 right-5 z-[600] flex items-center gap-2 border border-civic-success/40 bg-civic-surface px-4 py-3 text-sm shadow-panel"><ShieldCheck size={16} strokeWidth={1.6} className="text-green-300"/>Tracking link copied</motion.div>}</AnimatePresence>
  </div>
}
