import { motion, useReducedMotion } from 'framer-motion'
import { ArrowRight, CheckCircle2, MapPin, ScanLine, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PublicHeader } from '../components/Layout'
import { PriorityBadge, StatusBadge } from '../components/UI'

export default function Landing() {
  const reduce = useReducedMotion()
  return <div className="min-h-[100dvh] bg-civic-bg"><PublicHeader />
    <main>
      <section className="relative min-h-[100dvh] overflow-hidden border-b border-civic-border pt-20">
        <div className="pointer-events-none absolute inset-0 grid-signature opacity-[.14]" />
        <div className="pointer-events-none absolute bottom-0 right-0 h-[72%] w-[54%] carto-lines opacity-50" />
        <div className="shell relative grid min-h-[calc(100dvh-5rem)] items-center gap-14 py-20 lg:grid-cols-[.88fr_1.12fr] lg:py-24">
          <motion.div initial={reduce ? false : { opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .65 }}>
            <div className="mb-7 inline-flex items-center gap-2 border-l-2 border-civic-success bg-civic-secondary px-3 py-2 font-mono text-[10px] uppercase tracking-[.14em] text-civic-muted"><span className="h-1.5 w-1.5 rounded-full bg-civic-success" />Municipal response network online</div>
            <h1 className="max-w-[12ch] text-5xl font-semibold leading-[.98] tracking-[-.05em] text-civic-text sm:text-6xl lg:text-7xl">Report it. Track it. See your city respond.</h1>
            <p className="mt-7 max-w-xl text-base leading-7 text-civic-muted sm:text-lg">CivicTrack AI turns resident field reports into verified, prioritized public-works action—with every update visible from first photo to completed repair.</p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/login?role=citizen" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md bg-civic-accent px-5 text-sm font-semibold text-white transition-colors hover:bg-blue-700 active:scale-[.98]">Report an issue<ArrowRight size={17} strokeWidth={1.6} /></Link><Link to="/login" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md border border-civic-border bg-civic-surface px-5 text-sm font-semibold text-civic-text transition-colors hover:border-civic-muted active:scale-[.98]"><ShieldCheck size={17} strokeWidth={1.6} />Open demo workspace</Link></div>
            <div className="mt-10 grid max-w-lg grid-cols-3 divide-x divide-civic-border border-y border-civic-border py-4"><div><p className="data text-xl font-medium">4.2h</p><p className="mt-1 text-[11px] text-civic-muted">Median triage</p></div><div className="pl-4"><p className="data text-xl font-medium">87.4%</p><p className="mt-1 text-[11px] text-civic-muted">Verified in SLA</p></div><div className="pl-4"><p className="data text-xl font-medium">20</p><p className="mt-1 text-[11px] text-civic-muted">Active demo cases</p></div></div>
          </motion.div>
          <motion.div initial={reduce ? false : { opacity: 0, x: 28 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .75, delay: .12 }} className="relative lg:pl-8">
            <div className="absolute -left-5 top-14 hidden h-px w-16 bg-civic-accent lg:block" /><div className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-civic-border px-5 py-4"><div><p className="eyebrow">Resident tracking / live</p><p className="data mt-1 text-xs text-civic-text">CT-1001</p></div><StatusBadge status="in_progress" /></div><div className="grid md:grid-cols-[1.15fr_.85fr]"><div className="relative min-h-72 overflow-hidden border-b border-civic-border bg-civic-secondary md:border-b-0 md:border-r"><div className="absolute inset-0 grid-signature opacity-35" /><svg viewBox="0 0 500 330" className="absolute inset-0 h-full w-full" aria-label="Stylized complaint location map"><path d="M-20 260C105 202 154 290 266 203S386 122 530 174" fill="none" stroke="#263244" strokeWidth="44"/><path d="M-20 260C105 202 154 290 266 203S386 122 530 174" fill="none" stroke="#94A3B8" strokeOpacity=".36" strokeWidth="2" strokeDasharray="12 10"/><path d="M66 -20v380M184 -20v380M400 -20v380M-20 70h560M-20 298h560" stroke="#263244" strokeWidth="2"/><circle cx="294" cy="184" r="22" fill="#DC2626" fillOpacity=".18"/><circle cx="294" cy="184" r="8" fill="#DC2626" stroke="#F8FAFC" strokeWidth="3"/></svg><div className="absolute bottom-4 left-4 right-4 bg-civic-bg/95 p-3"><div className="flex items-center gap-2"><MapPin size={15} strokeWidth={1.6} className="text-civic-accent"/><span className="text-xs text-civic-text">Mercer Ave & 8th Street</span></div></div></div><div className="p-5"><div className="flex items-center justify-between"><PriorityBadge priority="critical"/><span className="data text-[10px] text-civic-muted">96% confidence</span></div><h2 className="mt-5 text-xl font-semibold leading-tight">Collapsed asphalt beside school crossing</h2><div className="mt-6 space-y-0">{[[CheckCircle2,'Report verified','08:14'],[ScanLine,'AI triage complete','08:17'],[ShieldCheck,'Crew dispatched','09:06']].map(([Icon,label,time], index) => <div key={label as string} className="relative flex gap-3 pb-5 last:pb-0"><div className="relative z-[1] grid h-7 w-7 shrink-0 place-items-center rounded-full border border-civic-success/50 bg-civic-success/10"><Icon size={14} strokeWidth={1.6} className="text-green-300"/></div>{index < 2 && <span className="absolute left-[13px] top-7 h-[calc(100%-1.75rem)] w-px bg-civic-border"/>}<div className="flex flex-1 justify-between gap-2 pt-1"><p className="text-xs text-civic-text">{label as string}</p><span className="data text-[10px] text-civic-muted">{time as string}</span></div></div>)}</div></div></div></div>
            <div className="ml-auto mt-3 flex w-fit items-center gap-2 border border-civic-border bg-civic-bg px-3 py-2 font-mono text-[9px] uppercase tracking-[.14em] text-civic-muted"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-civic-success"/>Public update verified</div>
          </motion.div>
        </div>
      </section>
      <section id="how-it-works" className="shell py-24 sm:py-32"><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow">One accountable workflow</p><h2 className="mt-3 max-w-md text-3xl font-semibold tracking-tight sm:text-4xl">Evidence in. Public action out.</h2><p className="mt-5 text-sm leading-6 text-civic-muted">Designed for real municipal service—not engagement metrics. Every report carries location, evidence, responsibility, and a visible outcome.</p></div><div className="border-t border-civic-border">{[['01','Capture','Add one clear image, a concise description, and verified location.'],['02','Assess','CivicTrack classifies impact, checks duplication, and routes the right team.'],['03','Resolve','Field crews attach completion evidence and residents see the result.']].map(row => <div key={row[0]} className="grid gap-3 border-b border-civic-border py-6 sm:grid-cols-[70px_170px_1fr]"><span className="data text-xs text-civic-accent">{row[0]}</span><h3 className="font-semibold">{row[1]}</h3><p className="text-sm leading-6 text-civic-muted">{row[2]}</p></div>)}</div></div></section>
    </main><footer className="border-t border-civic-border"><div className="shell flex flex-col gap-3 py-7 text-xs text-civic-muted sm:flex-row sm:items-center sm:justify-between"><p>CivicTrack AI · Demonstration municipal interface</p><Link to="/login" className="text-civic-text hover:text-blue-300">Access role workspaces</Link></div></footer>
  </div>
}
