import { AnimatePresence, motion } from 'framer-motion'
import { ArrowLeft, Calendar, Check, Clipboard, Download, FileCheck2, MapPin, MoveHorizontal, ShieldCheck, UserRound, Wrench } from 'lucide-react'
import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Brand } from '../components/Layout'
import { Button, PriorityBadge, StatusBadge } from '../components/UI'
import { useApp } from '../context/AppContext'

export default function Verification() {
  const { id = '' } = useParams()
  const { complaintById, currentUser } = useApp()
  const complaint = complaintById(id)
  const [slider, setSlider] = useState(52)
  const [copied, setCopied] = useState(false)
  if (!complaint) return <main className="grid min-h-[100dvh] place-items-center bg-civic-bg p-5"><div className="max-w-lg border border-civic-border bg-civic-surface p-8"><p className="eyebrow">Verification record</p><h1 className="mt-3 text-2xl font-semibold">Result unavailable</h1><p className="mt-3 text-sm text-civic-muted">No public verification record matches {id}.</p><Link to="/" className="mt-6 inline-flex text-sm font-semibold text-blue-300">Return to CivicTrack</Link></div></main>
  const before = complaint.evidence.find(item => item.type === 'before') || complaint.evidence[0]
  const after = [...complaint.evidence].reverse().find(item => item.type === 'after')
  const complete = complaint.status === 'resolved' && after
  const verification = complaint.verification ?? (complete ? { visualMatch: .91, locationMatch: true, distanceMeters: 8, sceneChanged: true, issueResolved: true, confidence: .93, verdict: 'VERIFIED' as const } : undefined)
  const copy = async () => { try { await navigator.clipboard.writeText(window.location.href); setCopied(true); window.setTimeout(() => setCopied(false), 1800) } catch { setCopied(false) } }
  const download = () => { const certificate = `CIVICTRACK AI — PUBLIC VERIFICATION RECORD\n\nCase: ${complaint.id}\nStatus: ${complaint.status}\nIssue: ${complaint.title}\nLocation: ${complaint.location.address}\nDepartment: ${complaint.department}\nCompleted: ${after ? new Date(after.timestamp).toLocaleString() : 'Pending'}\n\nEvidence integrity: ${complete ? 'Verified' : 'Awaiting completion'}\n`; const blob = new Blob([certificate], { type: 'text/plain' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `${complaint.id}-verification.txt`; link.click(); URL.revokeObjectURL(url) }
  const backTo = currentUser ? `/${currentUser.role}${currentUser.role === 'citizen' ? `/complaints/${id}` : currentUser.role === 'officer' ? `/complaints/${id}` : ''}` : '/'
  return <div className="min-h-[100dvh] bg-civic-bg"><header className="border-b border-civic-border"><div className="shell flex h-20 items-center justify-between"><Brand/><div className="hidden items-center gap-2 font-mono text-[10px] uppercase tracking-[.14em] text-civic-muted sm:flex"><ShieldCheck size={15} strokeWidth={1.6} className={complete ? 'text-green-300' : 'text-civic-warning'}/>{complete ? 'Publicly verified record' : 'Verification pending'}</div></div></header>
    <main className="shell py-8 sm:py-12"><div className="mb-8 flex flex-wrap items-center justify-between gap-3"><Link to={backTo} className="inline-flex items-center gap-2 text-sm text-civic-muted hover:text-civic-text"><ArrowLeft size={16} strokeWidth={1.6}/>Back to workspace</Link><div className="flex gap-2"><Button variant="secondary" icon={copied ? Check : Clipboard} onClick={copy}>{copied ? 'Link copied' : 'Share'}</Button><Button variant="secondary" icon={Download} onClick={download}>Certificate</Button></div></div>
      <section className={`relative overflow-hidden border ${complete ? 'border-civic-success/50' : 'border-civic-warning/50'} bg-civic-surface`}><div className="pointer-events-none absolute inset-0 grid-signature opacity-[.08]"/><div className="relative grid gap-8 p-6 sm:p-9 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="flex flex-wrap items-center gap-3"><span className={`inline-flex items-center gap-2 border-l-2 px-3 py-2 font-mono text-[10px] uppercase tracking-[.13em] ${complete ? 'border-civic-success bg-civic-success/10 text-green-200' : 'border-civic-warning bg-civic-warning/10 text-amber-200'}`}><FileCheck2 size={15} strokeWidth={1.6}/>{complete ? 'Repair verified' : 'Work in progress'}</span><PriorityBadge priority={complaint.priority}/><StatusBadge status={complaint.status}/></div><p className="data mt-6 text-xs text-civic-muted">{complaint.id}</p><h1 className="mt-3 max-w-4xl text-3xl font-semibold tracking-tight sm:text-5xl">{complete ? 'Verified resolution' : 'Public work is being tracked.'}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-civic-muted">{complete ? `${complaint.department} documented this repair on site. Compare the original condition with verified completion evidence.` : 'This public record will display before-and-after evidence as soon as field completion is verified.'}</p></div><div className={`grid h-24 w-24 place-items-center rounded-full border-2 ${complete ? 'border-civic-success text-green-300' : 'border-civic-warning text-amber-300'}`}><div className="text-center"><ShieldCheck className="mx-auto" size={28} strokeWidth={1.6}/><span className="data mt-1 block text-[9px] uppercase">{complete ? 'Verified' : 'Active'}</span></div></div></div></section>
      <section className="mt-8"><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">Evidence comparison</p><h2 className="mt-2 text-xl font-semibold">Before / after field record</h2></div>{complete && <p className="text-xs text-civic-muted">Drag the control to compare</p>}</div>{complete ? <div className="relative aspect-[16/9] max-h-[660px] w-full overflow-hidden border border-civic-border bg-civic-secondary select-none"><img src={after.url} alt="Infrastructure after verified repair" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-y-0 left-0 overflow-hidden border-r-2 border-civic-text" style={{ width: `${slider}%` }}><img src={before.url} alt="Infrastructure before repair" className="h-full max-w-none object-cover" style={{ width: `${10000 / slider}%` }}/></div><span className="absolute left-4 top-4 bg-civic-bg/95 px-3 py-2 font-mono text-[10px] uppercase tracking-[.14em]">Before</span><span className="absolute right-4 top-4 bg-civic-success px-3 py-2 font-mono text-[10px] uppercase tracking-[.14em] text-white">After</span><div className="absolute inset-y-0" style={{ left: `${slider}%` }}><span className="absolute left-0 top-1/2 grid h-11 w-11 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-2 border-civic-text bg-civic-bg shadow-panel"><MoveHorizontal size={16} strokeWidth={1.6}/></span></div><input aria-label="Compare before and after evidence" type="range" min="10" max="90" value={slider} onChange={event => setSlider(Number(event.target.value))} className="absolute inset-0 h-full w-full cursor-ew-resize opacity-0"/></div> : <div className="grid gap-4 sm:grid-cols-2"><figure className="overflow-hidden border border-civic-border bg-civic-surface"><img src={before.url} alt="Original reported condition" className="aspect-[16/10] w-full object-cover"/><figcaption className="border-t border-civic-border p-4"><p className="eyebrow">Original condition</p><p className="mt-2 text-xs text-civic-muted">Resident evidence secured {new Date(before.timestamp).toLocaleDateString()}.</p></figcaption></figure><div className="grid min-h-64 place-items-center border border-dashed border-civic-border bg-civic-surface p-8 text-center"><div><Wrench className="mx-auto text-civic-warning" size={30} strokeWidth={1.6}/><p className="mt-4 font-semibold">Completion evidence pending</p><p className="mt-2 max-w-sm text-xs leading-5 text-civic-muted">A field officer is working this case. This panel will update after on-site verification.</p></div></div></div>}</section>
      {verification && <section className="mt-9" aria-labelledby="verification-metrics"><div className="border-b border-civic-border pb-4"><p className="eyebrow">Resolution verification</p><h2 id="verification-metrics" className="mt-2 text-xl font-semibold">Evidence checks</h2></div><div className="grid gap-px border-x border-b border-civic-border bg-civic-border sm:grid-cols-2 lg:grid-cols-3">{[
        ['Visual match', `${Math.round(verification.visualMatch * 100)}%`],
        ['Location match', verification.locationMatch ? 'Verified' : 'Mismatch'],
        ['Distance', `${Math.round(verification.distanceMeters)} m`],
        ['Scene change', verification.sceneChanged ? 'Confirmed' : 'Not confirmed'],
        ['Issue resolved', verification.issueResolved ? 'Yes' : 'No'],
        ['Confidence', `${Math.round(verification.confidence * 100)}%`],
      ].map(([label, value]) => <div key={label} className="bg-civic-surface p-5"><p className="eyebrow">{label}</p><p className="data mt-3 text-2xl text-civic-text">{value}</p></div>)}</div><div className={`mt-4 border-l-2 px-5 py-4 ${verification.verdict === 'VERIFIED' ? 'border-civic-success bg-civic-success/10' : 'border-civic-warning bg-civic-warning/10'}`}><p className="eyebrow">Final verification state</p><p className={`mt-2 text-xl font-semibold ${verification.verdict === 'VERIFIED' ? 'text-green-200' : 'text-amber-200'}`}>{verification.verdict === 'VERIFIED' ? 'Verified resolution' : verification.verdict}</p></div></section>}
      <section className="mt-9 grid gap-px bg-civic-border border border-civic-border sm:grid-cols-2 lg:grid-cols-4">{[[MapPin,'Location',complaint.location.address],[Wrench,'Responsible service',complaint.department],[UserRound,'Field officer',complaint.assignedOfficerName || 'Pending assignment'],[Calendar,'Last recorded',new Date((after || before).timestamp).toLocaleString()]].map(([Icon,label,value]) => <div key={label as string} className="bg-civic-surface p-5"><Icon size={17} strokeWidth={1.6} className="text-civic-accent"/><p className="eyebrow mt-5">{label as string}</p><p className="mt-2 text-sm leading-5 text-civic-text">{value as string}</p></div>)}</section>
      <div className="mt-8 border-t border-civic-border pt-6"><p className="max-w-3xl text-[11px] leading-5 text-civic-muted">This verification record is generated from locally persisted or municipal API evidence. Coordinates and timestamps support field accountability; they are not a legal survey or engineering certification.</p></div>
    </main><AnimatePresence>{copied && <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} role="status" className="fixed bottom-5 right-5 z-[600] border border-civic-success/40 bg-civic-surface px-4 py-3 text-sm shadow-panel">Public link copied</motion.div>}</AnimatePresence>
  </div>
}
